# Generated by Django 4.0.3 on 2022-03-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_F_name', models.CharField(max_length=50)),
                ('student_M_name', models.CharField(max_length=50)),
                ('student_L_name', models.CharField(max_length=50)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('student_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.city_1')),
                ('student_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_csv.state_1')),
            ],
        ),
    ]
