# Generated by Django 4.0.3 on 2022-03-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_F_name', models.CharField(max_length=50)),
                ('student_M_name', models.CharField(max_length=50)),
                ('student_L_name', models.CharField(max_length=50)),
                ('student_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvfiles.city')),
                ('student_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvfiles.state')),
            ],
        ),
    ]
